### PR TITLE
Update library versions to fix build and revert i32 nonce

### PR DESCRIPTION
**Pull request by Acentelles**
Current `main` branch cannot build from scratch. The reason is that the dependency `aes = 0.5` depends on `aes-soft = 0.5.0`, which has been removed since (see v.0.5.0 in https://crates.io/crates/aes-soft/versions).

Updated `aes` to `0.7` and other related libraries with the corresponding code changes

### CODE REVIEW

**Comment by ggkitsas** [comment]
LGTM!

We should force-merge this PR, since we're caught in a deadlock (this solves a testing issue, other tests issues are yet to be unblocked).

@joebebel could you also check if these changes look good? Let's target to merge this by Friday?

**Review by ggkitsas — APPROVED** [review]

**Comment by Acentelles** [comment]
I think so, yes, unless you/me/we want to continue fixing the rest of the tests on this PR. cc @cwgoes

**Comment by ggkitsas** [comment]
I've included this PR in https://github.com/anoma/masp/pull/5 to unblock my flow (this wouldn't collide with merging this PR to main as I will rebase anyways).

https://github.com/anoma/masp/pull/5 seems better to continue fixing tests issues.

**Review by cwgoes — APPROVED** [review]
utACK

**Pull request merged**
